### PR TITLE
UI Updates

### PR DESCRIPTION
**Pull request by nishatfiroj**
work on issue #15

### CODE REVIEW

**Comment by tamara-tsubota** [comment]
It's a good start. The death count is still a button which can be confusing to users. Also in the future we need to fix the format for the results page and the filtering.

**Comment by jpbronsted** [comment]
Please avoid checking in large files that don't need to be checked in here. Like I said before, let's try to link to bootstrap files at their origin rather than import those files into this project. Additionally, let's move those images to Storage. I'll put in a PR after we finish the work here to also move the map image in the browse page to Storage.

**Comment by nishatfiroj** [comment]
> Please avoid checking in large files that don't need to be checked in here. Like I said before, let's try to link to bootstrap files at their origin rather than import those files into this project. Additionally, let's move those images to Storage. I'll put in a PR after we finish the work here to also move the map image in the browse page to Storage.

The reason I include bootstrap files directly instead of linking them is that it does make the website a little less stable, what with possible updates with the online versions of bootstrap. do we still want there to be a link in that case?

**Comment by jpbronsted** [comment]
> > Please avoid checking in large files that don't need to be checked in here. Like I said before, let's try to link to bootstrap files at their origin rather than import those files into this project. Additionally, let's move those images to Storage. I'll put in a PR after we finish the work here to also move the map image in the browse page to Storage.
> 
> The reason I include bootstrap files directly instead of linking them is that it does make the website a little less stable, what with possible updates with the online versions of bootstrap. do we still want there to be a link in that case?

Good point, let's keep them in then.

**Comment by jpbronsted** [comment]
I had a look at the changes through the present and they look good. We should merge this soon so that we can open up a few small final touches issues.

**Pull request merged**
