### PR TITLE
made changes to browse.html pursuant to #3; also added a results page

### PR DESCRIPTION
**Pull request by jpbronsted**
The browse page (browse.html) now has a drop-down menu with submit button and a clickable map that allow the user to submit a province for querying. Both the submit button and the map clickable areas take the user to a new results page (results.php) which for now just prints out the province the user asked for. In a later sprint, we will connect this php script to a database to query and display content.

I also checked in two different versions of the map: one with the province names and one that is blank. The browse page currently uses the filled-in map, but we may want to switch it to the blank one to overlay with nice UI later, so I'll check in both.

### CODE REVIEW

**Comment by jpbronsted** [comment]
Note: I just realized that this PR also resolved issue #2

**Comment by tamara-tsubota** [comment]
Just a note, I think the "View Documents" button should be closer to the dropdown, but it looks good to me!

**Comment by jpbronsted** [comment]
Do you think I should I place the “View Documents” button above the map?

**Comment by tamara-tsubota** [comment]
Wait, I might be confused. Is the that button the submit button for the dropdown or a button to see all providences?

**Comment by jpbronsted** [comment]
The “View Documents” button submits a form which indirectly gets its fields from the drop-down. One of the drop-down options is to view all provinces. The “View Documents” button has no relation to the clickable map.

**Comment by tamara-tsubota** [comment]
I think it should go next to the dropdown. It looks really random where it is right now and it took me awhile to figure out that it was related to the dropdown list.

**Comment by jpbronsted** [comment]
Most recent commit has the drop-down moved above the image.

**Pull request merged**
